/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "MailBox.h"

bool_t
xdr_str_t(xdrs, objp)
	XDR *xdrs;
	str_t *objp;
{

	if (!xdr_string(xdrs, objp, 81))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_string_wrapper(xdrs, objp)
	XDR *xdrs;
	string_wrapper *objp;
{

	if (!xdr_str_t(xdrs, &objp->data))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_retrieve_message_params(xdrs, objp)
	XDR *xdrs;
	retrieve_message_params *objp;
{

	if (!xdr_user(xdrs, &objp->given_user))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->message_number))
		return (FALSE);
	if (!xdr_string_wrapper(xdrs, &objp->message))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_delete_message_params(xdrs, objp)
	XDR *xdrs;
	delete_message_params *objp;
{

	if (!xdr_user(xdrs, &objp->given_user))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->message_number))
		return (FALSE);
	return (TRUE);
}
