/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "MailBox.h"

bool_t
xdr_user(xdrs, objp)
	XDR *xdrs;
	user *objp;
{

	if (!xdr_string(xdrs, &objp->hostname, 50))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->uuid))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_retrieve_message_params(xdrs, objp)
	XDR *xdrs;
	retrieve_message_params *objp;
{

	if (!xdr_user(xdrs, &objp->given_user))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->message_number))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_delete_message_params(xdrs, objp)
	XDR *xdrs;
	delete_message_params *objp;
{

	if (!xdr_user(xdrs, &objp->given_user))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->message_number))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_message_block(xdrs, objp)
	XDR *xdrs;
	message_block *objp;
{

	if (!xdr_string(xdrs, &objp->data, 1600))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_insert_message_params(xdrs, objp)
	XDR *xdrs;
	insert_message_params *objp;
{

	if (!xdr_user(xdrs, &objp->given_user))
		return (FALSE);
	if (!xdr_string(xdrs, &objp->message, 80))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->message_number))
		return (FALSE);
	return (TRUE);
}
