/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MAILBOX_H_RPCGEN
#define _MAILBOX_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>


struct user {
	char *hostname;
	int uuid;
};
typedef struct user user;
#ifdef __cplusplus
extern "C" bool_t xdr_user(XDR *, user*);
#elif __STDC__
extern  bool_t xdr_user(XDR *, user*);
#else /* Old Style C */
bool_t xdr_user();
#endif /* Old Style C */


struct retrieve_message_params {
	user given_user;
	int message_number;
};
typedef struct retrieve_message_params retrieve_message_params;
#ifdef __cplusplus
extern "C" bool_t xdr_retrieve_message_params(XDR *, retrieve_message_params*);
#elif __STDC__
extern  bool_t xdr_retrieve_message_params(XDR *, retrieve_message_params*);
#else /* Old Style C */
bool_t xdr_retrieve_message_params();
#endif /* Old Style C */


struct delete_message_params {
	user given_user;
	int message_number;
};
typedef struct delete_message_params delete_message_params;
#ifdef __cplusplus
extern "C" bool_t xdr_delete_message_params(XDR *, delete_message_params*);
#elif __STDC__
extern  bool_t xdr_delete_message_params(XDR *, delete_message_params*);
#else /* Old Style C */
bool_t xdr_delete_message_params();
#endif /* Old Style C */


struct message_block {
	char *data;
};
typedef struct message_block message_block;
#ifdef __cplusplus
extern "C" bool_t xdr_message_block(XDR *, message_block*);
#elif __STDC__
extern  bool_t xdr_message_block(XDR *, message_block*);
#else /* Old Style C */
bool_t xdr_message_block();
#endif /* Old Style C */


struct insert_message_params {
	user given_user;
	char *message;
	int message_number;
};
typedef struct insert_message_params insert_message_params;
#ifdef __cplusplus
extern "C" bool_t xdr_insert_message_params(XDR *, insert_message_params*);
#elif __STDC__
extern  bool_t xdr_insert_message_params(XDR *, insert_message_params*);
#else /* Old Style C */
bool_t xdr_insert_message_params();
#endif /* Old Style C */


#define DISPLAY_PRG ((rpc_uint)0x20000001)
#define DISPLAY_VER ((rpc_uint)1)

#ifdef __cplusplus
#define start ((rpc_uint)1)
extern "C" int * start_1(user *, CLIENT *);
extern "C" int * start_1_svc(user *, struct svc_req *);
#define quit ((rpc_uint)2)
extern "C" int * quit_1(user *, CLIENT *);
extern "C" int * quit_1_svc(user *, struct svc_req *);
#define retrieve_message ((rpc_uint)3)
extern "C" char ** retrieve_message_1(retrieve_message_params *, CLIENT *);
extern "C" char ** retrieve_message_1_svc(retrieve_message_params *, struct svc_req *);
#define list_all_messages ((rpc_uint)4)
extern "C" message_block * list_all_messages_1(user *, CLIENT *);
extern "C" message_block * list_all_messages_1_svc(user *, struct svc_req *);
#define delete_message ((rpc_uint)5)
extern "C" int * delete_message_1(delete_message_params *, CLIENT *);
extern "C" int * delete_message_1_svc(delete_message_params *, struct svc_req *);
#define insert_message ((rpc_uint)6)
extern "C" int * insert_message_1(insert_message_params *, CLIENT *);
extern "C" int * insert_message_1_svc(insert_message_params *, struct svc_req *);

#elif __STDC__
#define start ((rpc_uint)1)
extern  int * start_1(user *, CLIENT *);
extern  int * start_1_svc(user *, struct svc_req *);
#define quit ((rpc_uint)2)
extern  int * quit_1(user *, CLIENT *);
extern  int * quit_1_svc(user *, struct svc_req *);
#define retrieve_message ((rpc_uint)3)
extern  char ** retrieve_message_1(retrieve_message_params *, CLIENT *);
extern  char ** retrieve_message_1_svc(retrieve_message_params *, struct svc_req *);
#define list_all_messages ((rpc_uint)4)
extern  message_block * list_all_messages_1(user *, CLIENT *);
extern  message_block * list_all_messages_1_svc(user *, struct svc_req *);
#define delete_message ((rpc_uint)5)
extern  int * delete_message_1(delete_message_params *, CLIENT *);
extern  int * delete_message_1_svc(delete_message_params *, struct svc_req *);
#define insert_message ((rpc_uint)6)
extern  int * insert_message_1(insert_message_params *, CLIENT *);
extern  int * insert_message_1_svc(insert_message_params *, struct svc_req *);

#else /* Old Style C */
#define start ((rpc_uint)1)
extern  int * start_1();
extern  int * start_1_svc();
#define quit ((rpc_uint)2)
extern  int * quit_1();
extern  int * quit_1_svc();
#define retrieve_message ((rpc_uint)3)
extern  char ** retrieve_message_1();
extern  char ** retrieve_message_1_svc();
#define list_all_messages ((rpc_uint)4)
extern  message_block * list_all_messages_1();
extern  message_block * list_all_messages_1_svc();
#define delete_message ((rpc_uint)5)
extern  int * delete_message_1();
extern  int * delete_message_1_svc();
#define insert_message ((rpc_uint)6)
extern  int * insert_message_1();
extern  int * insert_message_1_svc();
#endif /* Old Style C */

#endif /* !_MAILBOX_H_RPCGEN */
